name: 'Render message'
description: 'Renders message for input and channel type'
inputs:
  # github context
  repository:
    description: github repository
    required: true
  ref:
    description: github ref
    required: true
  actor:
    description: github actor
    required: true
  run_id:
    description: github run_id
    required: true
  sha:
    description: github sha
    required: true

  # regular input parameters
  tool:
    description: 'name of tool'
    required: true
  input-file:
    description: 'input file name'
    required: true
  output-file:
    description: 'output file name'
    required: true
  renderer:
    description: 'name of renderer'
    required: true
outputs:
  message-file:
    description: 'file containing renedered message'
  isEmpty:
    description: 'Boolean to check that the message is not empty'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.ref }}
    - ${{ inputs.actor }}
    - ${{ inputs.run_id }}
    - ${{ inputs.sha }}
    - ${{ inputs.tool }}
    - ${{ inputs.input-file }}
    - ${{ inputs.output-file }}
    - ${{ inputs.renderer }}
